import { Hero } from "@/types/hero"

export const heroes: Hero[] = [
  { id: 1, name: "Aamon", roles: ["Jungle"], specialty: "Assassin / Mage", damageType: "Magic", tags: ["Burst", "Pickoff"] },
  { id: 2, name: "Akai", roles: ["Roam", "Jungle", "EXP"], specialty: "Tank", damageType: "Physical", tags: ["Frontline", "Engage", "CC", "Disengage"] },
  { id: 3, name: "Aldous", roles: ["EXP"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "Scaling"] },
  { id: 4, name: "Alice", roles: ["EXP", "Jungle"], specialty: "Tank / Mage", damageType: "Magic", tags: ["Frontline", "Sustain", "Scaling"] },
  { id: 5, name: "Alpha", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Sustain"] },
  { id: 6, name: "Alucard", roles: ["Jungle", "EXP"], specialty: "Fighter / Assassin", damageType: "Physical", tags: ["Burst", "Sustain"] },
  { id: 7, name: "Angela", roles: ["Roam", "Mid"], specialty: "Support", damageType: "Magic", tags: ["Utility", "Peel", "Disengage"] },
  { id: 8, name: "Argus", roles: ["EXP"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 9, name: "Arlott", roles: ["EXP", "Roam"], specialty: "Fighter", damageType: "Physical", tags: ["Engage", "CC", "Pickoff"] },
  { id: 10, name: "Atlas", roles: ["Roam"], specialty: "Tank", damageType: "Magic", tags: ["Frontline", "Engage", "CC"] },
  { id: 11, name: "Aulus", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 12, name: "Aurora", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "CC"] },

  { id: 13, name: "Badang", roles: ["EXP", "Roam"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "CC"] },
  { id: 14, name: "Balmond", roles: ["EXP", "Jungle"], specialty: "Fighter / Tank", damageType: "Physical", tags: ["Frontline", "Sustain", "Early"] },
  { id: 15, name: "Bane", roles: ["EXP", "Mid", "Gold"], specialty: "Fighter / Mage", damageType: "Mixed", tags: ["Poke", "Sustain"] },
  { id: 16, name: "Barats", roles: ["Jungle", "Roam", "EXP"], specialty: "Tank / Fighter", damageType: "Physical", tags: ["Frontline", "Engage", "CC"] },
  { id: 17, name: "Baxia", roles: ["Jungle", "Roam"], specialty: "Tank", damageType: "Magic", tags: ["Frontline", "Utility"] },
  { id: 18, name: "Beatrix", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Burst", "DPS", "Scaling"] },
  { id: 19, name: "Belerick", roles: ["Roam", "EXP"], specialty: "Tank", damageType: "Magic", tags: ["Frontline", "CC", "Peel", "Disengage"] },
  { id: 20, name: "Benedetta", roles: ["EXP", "Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Pickoff", "Early"] },
  { id: 21, name: "Brody", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Burst", "Scaling"] },
  { id: 22, name: "Bruno", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Burst", "Scaling"] },

  { id: 23, name: "Carmilla", roles: ["Roam"], specialty: "Support / Tank", damageType: "Magic", tags: ["CC", "Utility", "Engage"] },
  { id: 24, name: "Cecilion", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Scaling", "Poke"] },
  { id: 25, name: "Chang'e", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Poke", "DPS"] },
  { id: 26, name: "Chip", roles: ["Roam"], specialty: "Tank / Support", damageType: "Magic", tags: ["Utility", "Engage", "Peel", "Disengage"] },
  { id: 27, name: "Chou", roles: ["EXP", "Roam"], specialty: "Fighter", damageType: "Physical", tags: ["Pickoff", "CC", "Utility"] },
  { id: 28, name: "Claude", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 29, name: "Clint", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Burst", "Poke"] },
  { id: 30, name: "Cici", roles: ["EXP"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Sustain"] },
  { id: 31, name: "Cyclops", roles: ["Mid", "Jungle"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "DPS"] },

  { id: 32, name: "Diggie", roles: ["Roam"], specialty: "Support", damageType: "Magic", tags: ["Utility", "Peel", "Disengage"] },
  { id: 33, name: "Dyrroth", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "Early"] },

  { id: 34, name: "Edith", roles: ["Roam", "EXP", "Gold"], specialty: "Tank / Marksman", damageType: "Mixed", tags: ["Frontline", "CC", "DPS"] },
  { id: 35, name: "Esmeralda", roles: ["EXP", "Mid", "Roam"], specialty: "Mage / Tank", damageType: "Magic", tags: ["Frontline", "Sustain"] },
  { id: 36, name: "Estes", roles: ["Roam"], specialty: "Support", damageType: "Magic", tags: ["Sustain", "Utility", "Peel", "Disengage"] },
  { id: 37, name: "Eudora", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "CC"] },

  { id: 38, name: "Fanny", roles: ["Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Early", "Pickoff"] },
  { id: 39, name: "Faramis", roles: ["Roam", "Mid"], specialty: "Support / Mage", damageType: "Magic", tags: ["Utility", "CC", "Disengage"] },
  { id: 40, name: "Floryn", roles: ["Roam"], specialty: "Support", damageType: "Magic", tags: ["Sustain", "Utility"] },
  { id: 41, name: "Franco", roles: ["Roam"], specialty: "Tank", damageType: "Physical", tags: ["Pickoff", "CC"] },
  { id: 42, name: "Fredrinn", roles: ["Jungle", "EXP"], specialty: "Tank / Fighter", damageType: "Physical", tags: ["Frontline", "Engage", "Sustain", "CC"] },
  { id: 43, name: "Freya", roles: ["EXP", "Jungle", "Gold"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Early"] },

  { id: 44, name: "Gatotkaca", roles: ["EXP", "Roam"], specialty: "Tank / Fighter", damageType: "Magic", tags: ["Frontline", "Engage", "CC"] },
  { id: 45, name: "Gloo", roles: ["EXP", "Roam"], specialty: "Tank", damageType: "Magic", tags: ["Frontline", "CC", "Sustain"] },
  { id: 46, name: "Gord", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["DPS", "Poke"] },
  { id: 47, name: "Granger", roles: ["Gold", "Jungle"], specialty: "Marksman", damageType: "Physical", tags: ["Burst", "Early"] },
  { id: 48, name: "Grock", roles: ["Roam", "EXP"], specialty: "Tank", damageType: "Physical", tags: ["Frontline", "Utility", "Engage"] },
  { id: 49, name: "Guinevere", roles: ["EXP", "Roam", "Jungle"], specialty: "Fighter / Mage", damageType: "Magic", tags: ["Burst", "CC"] },
  { id: 50, name: "Gusion", roles: ["Jungle"], specialty: "Assassin / Mage", damageType: "Magic", tags: ["Burst", "Pickoff"] },

  { id: 51, name: "Hanabi", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 52, name: "Hanzo", roles: ["Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Pickoff"] },
  { id: 53, name: "Harith", roles: ["Mid", "Gold"], specialty: "Mage", damageType: "Magic", tags: ["DPS", "Scaling"] },
  { id: 54, name: "Harley", roles: ["Mid", "Jungle"], specialty: "Mage / Assassin", damageType: "Magic", tags: ["Burst", "Pickoff"] },
  { id: 55, name: "Hayabusa", roles: ["Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Pickoff"] },
  { id: 56, name: "Helcurt", roles: ["Jungle", "Roam"], specialty: "Assassin", damageType: "Physical", tags: ["Pickoff", "Burst", "Early"] },
  { id: 57, name: "Hilda", roles: ["EXP", "Roam"], specialty: "Fighter / Tank", damageType: "Physical", tags: ["Frontline", "Early", "Sustain"] },
  { id: 58, name: "Hylos", roles: ["Roam", "EXP"], specialty: "Tank", damageType: "Magic", tags: ["Frontline", "Peel", "Engage", "Disengage"] },

  { id: 59, name: "Irithel", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 60, name: "Ixia", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },

  { id: 61, name: "Jawhead", roles: ["Roam", "EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["Pickoff", "Utility", "Early"] },
  { id: 62, name: "Johnson", roles: ["Roam"], specialty: "Tank", damageType: "Magic", tags: ["Engage", "CC"] },
  { id: 63, name: "Joy", roles: ["Jungle"], specialty: "Assassin", damageType: "Magic", tags: ["Burst", "Early"] },
  { id: 64, name: "Julian", roles: ["Jungle", "EXP", "Mid"], specialty: "Fighter / Mage", damageType: "Mixed", tags: ["Burst", "Pickoff", "Early"] },

  { id: 65, name: "Kadita", roles: ["Mid", "Roam"], specialty: "Mage / Assassin", damageType: "Magic", tags: ["Burst", "Engage"] },
  { id: 66, name: "Kagura", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "Poke"] },
  { id: 67, name: "Kaja", roles: ["Roam", "EXP"], specialty: "Support / Fighter", damageType: "Magic", tags: ["Pickoff", "Utility", "CC"] },
  { id: 68, name: "Kalea", roles: ["Roam"], specialty: "Support / Fighter", damageType: "Physical", tags: ["Engage", "Peel", "Utility", "Disengage"] },
  { id: 69, name: "Karina", roles: ["Jungle"], specialty: "Assassin", damageType: "Magic", tags: ["Burst", "Pickoff"] },
  { id: 70, name: "Karrie", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 71, name: "Khaleed", roles: ["EXP", "Roam"], specialty: "Fighter", damageType: "Physical", tags: ["Sustain", "Early"] },
  { id: 72, name: "Khufra", roles: ["Roam"], specialty: "Tank", damageType: "Physical", tags: ["Engage", "CC", "Frontline"] },
  { id: 73, name: "Kimmy", roles: ["Gold", "Mid"], specialty: "Marksman / Mage", damageType: "Mixed", tags: ["DPS", "Poke"] },

  { id: 74, name: "Lancelot", roles: ["Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Pickoff"] },
  { id: 75, name: "Lapu-Lapu", roles: ["EXP"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "Frontline"] },
  { id: 76, name: "Layla", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Scaling", "DPS"] },
  { id: 77, name: "Leomord", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "Scaling"] },
  { id: 78, name: "Lesley", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Burst", "Scaling"] },
  { id: 79, name: "Ling", roles: ["Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Pickoff"] },
  { id: 80, name: "Lolita", roles: ["Roam"], specialty: "Tank / Support", damageType: "Physical", tags: ["Peel", "Frontline", "CC", "Disengage"] },
  { id: 81, name: "Lukas", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "Early"] },
  { id: 82, name: "Lunox", roles: ["Mid", "Gold"], specialty: "Mage", damageType: "Mixed", tags: ["Burst", "Scaling"] },
  { id: 83, name: "Luo Yi", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["CC", "Utility", "Poke"] },
  { id: 84, name: "Lylia", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "Early"] },

  { id: 85, name: "Marcel", roles: ["Roam"], specialty: "Support", damageType: "Magic", tags: ["Utility", "Peel", "Disengage"] },
  { id: 86, name: "Martis", roles: ["Jungle", "EXP"], specialty: "Fighter", damageType: "Physical", tags: ["CC", "Early", "Pickoff"] },
  { id: 87, name: "Masha", roles: ["EXP", "Roam"], specialty: "Fighter / Tank", damageType: "Physical", tags: ["Frontline", "DPS"] },
  { id: 88, name: "Mathilda", roles: ["Roam"], specialty: "Support / Assassin", damageType: "Magic", tags: ["Engage", "Utility", "Pickoff"] },
  { id: 89, name: "Melissa", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 90, name: "Minotauro", roles: ["Roam"], specialty: "Tank / Support", damageType: "Physical", tags: ["Frontline", "CC", "Sustain"] },
  { id: 91, name: "Miya", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["Scaling", "DPS"] },
  { id: 92, name: "Minsitthar", roles: ["EXP", "Roam"], specialty: "Fighter", damageType: "Physical", tags: ["CC", "Utility", "Peel", "Disengage"] },
  { id: 93, name: "Moskov", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },

  { id: 94, name: "Nana", roles: ["Mid", "Roam"], specialty: "Mage / Support", damageType: "Magic", tags: ["Burst", "Peel", "CC", "Disengage"] },
  { id: 95, name: "Natalia", roles: ["Roam", "Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Pickoff", "Burst"] },
  { id: 96, name: "Natan", roles: ["Gold", "Mid"], specialty: "Marksman / Mage", damageType: "Magic", tags: ["DPS", "Scaling"] },
  { id: 97, name: "Nolan", roles: ["Jungle"], specialty: "Assassin", damageType: "Physical", tags: ["Burst", "Early"] },
  { id: 98, name: "Novaria", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Poke", "Utility"] },

  { id: 99, name: "Obsidia", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 100, name: "Odette", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "CC"] },

  { id: 101, name: "Paquito", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["Burst", "Early"] },
  { id: 102, name: "Pharsa", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Poke", "Burst"] },
  { id: 103, name: "Phoveus", roles: ["EXP"], specialty: "Fighter", damageType: "Magic", tags: ["CC", "Burst"] },
  { id: 104, name: "Popol and Kupa", roles: ["Gold", "Roam"], specialty: "Marksman / Support", damageType: "Physical", tags: ["Pickoff", "Utility", "DPS"] },

  { id: 105, name: "Rafaela", roles: ["Roam"], specialty: "Support", damageType: "Magic", tags: ["Utility", "Peel", "Sustain", "Disengage"] },
  { id: 106, name: "Roger", roles: ["Gold", "Jungle", "EXP"], specialty: "Marksman / Fighter", damageType: "Physical", tags: ["DPS", "Early", "Scaling"] },
  { id: 107, name: "Ruby", roles: ["EXP", "Roam"], specialty: "Fighter / Tank", damageType: "Physical", tags: ["Sustain", "CC", "Frontline"] },

  { id: 108, name: "Saber", roles: ["Jungle", "Roam"], specialty: "Assassin", damageType: "Physical", tags: ["Pickoff", "Burst"] },
  { id: 109, name: "Selena", roles: ["Mid", "Roam"], specialty: "Assassin / Mage", damageType: "Magic", tags: ["Pickoff", "Burst", "CC"] },
  { id: 110, name: "Silvanna", roles: ["EXP", "Jungle"], specialty: "Fighter / Mage", damageType: "Magic", tags: ["Engage", "CC"] },
  { id: 111, name: "Sora", roles: ["EXP", "Jungle"], specialty: "Fighter / Assassin", damageType: "Physical", tags: ["Burst", "Early"] },
  { id: 112, name: "Sun", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Scaling"] },
  { id: 113, name: "Suyou", roles: ["Jungle", "EXP"], specialty: "Assassin / Fighter", damageType: "Physical", tags: ["Burst", "Early"] },

  { id: 114, name: "Terizla", roles: ["EXP"], specialty: "Fighter / Tank", damageType: "Physical", tags: ["Frontline", "CC"] },
  { id: 115, name: "Thamuz", roles: ["EXP"], specialty: "Fighter", damageType: "Physical", tags: ["DPS", "Sustain"] },
  { id: 116, name: "Tigreal", roles: ["Roam"], specialty: "Tank", damageType: "Physical", tags: ["Frontline", "Engage", "CC"] },

  { id: 117, name: "Uranus", roles: ["EXP"], specialty: "Tank", damageType: "Magic", tags: ["Frontline", "Sustain"] },

  { id: 118, name: "Vale", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "CC"] },
  { id: 119, name: "Valentina", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "Utility", "Pickoff"] },
  { id: 120, name: "Valir", roles: ["Mid", "Roam"], specialty: "Mage", damageType: "Magic", tags: ["Poke", "Peel", "Utility", "Disengage"] },
  { id: 121, name: "Vexana", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["CC", "Utility"] },

  { id: 122, name: "Wanwan", roles: ["Gold"], specialty: "Marksman", damageType: "Physical", tags: ["DPS", "Scaling"] },

  { id: 123, name: "X-Borg", roles: ["EXP", "Jungle"], specialty: "Fighter", damageType: "Mixed", tags: ["DPS", "Sustain"] },
  { id: 124, name: "Xavier", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Poke", "Scaling"] },

  { id: 125, name: "Yi Sun-shin", roles: ["Jungle", "Gold"], specialty: "Marksman / Assassin", damageType: "Physical", tags: ["Burst", "Scaling"] },
  { id: 126, name: "Yin", roles: ["EXP", "Jungle"], specialty: "Fighter / Assassin", damageType: "Physical", tags: ["Pickoff", "Burst"] },
  { id: 127, name: "Yu Zhong", roles: ["EXP"], specialty: "Fighter", damageType: "Physical", tags: ["Frontline", "Sustain"] },
  { id: 128, name: "Yve", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Poke", "Utility"] },

  { id: 129, name: "Zhask", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["DPS", "Poke"] },
  { id: 130, name: "Zhuxin", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["CC", "Utility"] },
  { id: 131, name: "Zetian", roles: ["Mid"], specialty: "Mage", damageType: "Magic", tags: ["Burst", "Poke"] },
  { id: 132, name: "Zilong", roles: ["EXP", "Jungle"], specialty: "Fighter / Assassin", damageType: "Physical", tags: ["Pickoff", "Scaling"] },
]